wallpaper {
    monitor = DP-1
    path = /home/maoto/.wallpapers/wpp3.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/maoto/.wallpapers/wpp3.jpg
    fit_mode = cover
}

splash = false
